server:
  port: 8088

ahrpc:
  providers: http://localhost:8081/,http://localhost:8082/,http://localhost:8083/
  zkServer: localhost:2181
  zkRoot: ahRpc
app:
  id: app1
  env: dev
  namespace: public

logging:
  level:
    root: info
    cn.hjh.ahrpc: debug