### 查询用户
POST http://localhost:8081/
#POST http://192.168.2.9:8081/
Content-Type: application/json

{
  "service":"cn.hjh.ahrpc.demo.api.UserService",
  "methodSign":"findById@1_class java.lang.Integer",
  "args": [100]
}

### 查询用户8082
POST http://localhost:8082/
Content-Type: application/json

{
  "service":"cn.hjh.ahrpc.demo.api.UserService",
  "methodSign":"findById@1_class java.lang.Integer",
  "args": [100]
}

### 查询用户8088
GET http://localhost:8088/?id=678

### 查询用户 2 个参数
POST http://localhost:8081/
Content-Type: application/json

{
  "service":"cn.hjh.ahrpc.demo.api.UserService",
  "methodSign":"findById@2_class java.lang.Integer_class java.lang.String",
  "args": [98,"sx"]
}

###查询订单
POST http://localhost:8082/
Content-Type: application/json

{
  "service":"cn.hjh.ahrpc.demo.api.OrderService",
  "methodSign":"findById@1_class java.lang.Integer",
  "args": [3]
}